import { cp, mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const dist = join(root, 'dist');
const site = JSON.parse(await readFile(join(root, 'src/content/site.json'), 'utf8'));
const esc = (value) => String(value).replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;');

await rm(dist, { recursive: true, force: true });
await mkdir(join(dist, 'assets'), { recursive: true });
await cp(join(root, 'src/styles/global.css'), join(dist, 'assets/global.css'));
await cp(join(root, 'public/assets/finanzplanung-konzept-v2.webp'), join(dist, 'assets/finanzplanung-konzept-v2.webp'));
await cp(join(root, 'public/robots.txt'), join(dist, 'robots.txt'));

const nav = site.navigation.map((item) => `<a href="${esc(item.href)}">${esc(item.label)}</a>`).join('');
const trust = site.trust.map((item) => `<li><span>${esc(item.label)}</span><strong>${esc(item.value)}</strong></li>`).join('');
const html = `<!doctype html><html lang="de"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width"><meta name="robots" content="noindex, nofollow, noarchive"><meta name="theme-color" content="#151715"><meta name="description" content="Akquise-Konzept für MH-Invest GmbH: persönliche Beratung zu Versicherungen, Finanzen und Investment in Hagen."><title>MH-Invest | Akquise-Hero Konzept</title><link rel="stylesheet" href="/assets/global.css"></head><body id="top">
<aside class="demo-notice" aria-label="Hinweis zur Präsentationsdemo">Akquise-Demo · KI-generiertes Konzeptmotiv · nicht zur Veröffentlichung</aside><section class="hero" aria-labelledby="hero-title"><header class="site-header"><a class="brand" href="#top" aria-label="${esc(site.company)} – Startseite"><span class="brand-mark" aria-hidden="true">MH</span><span class="brand-copy"><strong>${esc(site.brand)}</strong><small>${esc(site.claim)}</small></span></a><nav class="desktop-nav" aria-label="Hauptnavigation">${nav}</nav><a class="header-contact" href="#kontakt">Kontakt <span aria-hidden="true">↗</span></a><button class="menu-toggle" type="button" aria-expanded="false" aria-controls="mobile-nav" aria-label="Navigation öffnen"><span></span><span></span></button></header><nav class="mobile-nav" id="mobile-nav" aria-label="Mobile Navigation" hidden>${nav}<a href="#kontakt">Kontakt</a></nav><img class="hero-media" src="/assets/finanzplanung-konzept-v2.webp" alt="Konzeptmotiv eines persönlichen Finanzplans mit Diagnosegrafik und einem klar markierten Weg" width="1672" height="941" fetchpriority="high"><div class="hero-shade" aria-hidden="true"></div><div class="hero-content"><p class="eyebrow">${esc(site.eyebrow)}</p><p class="hero-brand">${esc(site.brand)}</p><h1 id="hero-title">${esc(site.headline)}</h1><p class="hero-intro">${esc(site.intro)}</p><div class="hero-actions"><a class="button button-primary" href="#kontakt">${esc(site.primaryCta)} <span aria-hidden="true">↗</span></a><a class="button button-secondary" href="#leistungen">${esc(site.secondaryCta)}</a></div></div><div class="hero-footer"><ul class="trust-list" aria-label="Nachgewiesene Merkmale">${trust}</ul></div></section>
<main><section class="intro-section" id="profil" aria-labelledby="profil-title"><p class="section-kicker">Finanzdiagnostik</p><div><h2 id="profil-title">Erst verstehen. Dann entscheiden.</h2><p class="section-lead">Versicherungen, Vorsorge und Geldanlage greifen ineinander. MH-Invest verbindet persönliche Beratung mit digitalen Vergleichsmöglichkeiten und einem klaren Blick auf Ihre Situation.</p></div></section><section class="services" id="leistungen" aria-labelledby="services-title"><div class="section-heading"><p class="section-kicker">Leistungsfelder</p><h2 id="services-title">Ein Ansprechpartner.<br>Vier Perspektiven.</h2></div><div class="service-list"><article><span>01</span><h3>Versicherungen</h3><p>Absicherung für Alltag, Eigentum und Mobilität.</p></article><article><span>02</span><h3>Vorsorge</h3><p>Finanzielle Planung für verschiedene Lebensphasen.</p></article><article><span>03</span><h3>Finanzierung</h3><p>Vergleichsmöglichkeiten für Kredite und Bankprodukte.</p></article><article><span>04</span><h3>Investment</h3><p>Orientierung bei Anlageklassen und Vermögensaufbau.</p></article></div></section><section class="contact-section" id="kontakt" aria-labelledby="contact-title"><div><p class="section-kicker">Direkter Kontakt</p><h2 id="contact-title">Ihre Lösung beginnt mit einem klaren Gespräch.</h2></div><div class="contact-links"><a href="${esc(site.phoneHref)}">${esc(site.phone)}<span>Telefon</span></a><a href="${esc(site.emailHref)}">${esc(site.email)}<span>E-Mail</span></a><p>${esc(site.address)}<span>Standort</span></p></div></section></main><footer><p>MH-Invest GmbH · Akquise-Konzept · Nicht zur Veröffentlichung</p><a href="#top">Nach oben ↑</a></footer>
<script>const t=document.querySelector('.menu-toggle'),n=document.querySelector('.mobile-nav');t?.addEventListener('click',()=>{const o=t.getAttribute('aria-expanded')==='true';t.setAttribute('aria-expanded',String(!o));t.setAttribute('aria-label',o?'Navigation öffnen':'Navigation schließen');if(n)n.hidden=o;document.body.classList.toggle('menu-open',!o)});n?.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{t?.setAttribute('aria-expanded','false');t?.setAttribute('aria-label','Navigation öffnen');n.hidden=true;document.body.classList.remove('menu-open')}));</script></body></html>`;
await writeFile(join(dist, 'index.html'), html);
console.log(`QA preview built at ${join(dist, 'index.html')}`);
